services:
  mysql:
    image: mysql:8
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${MYSQL_DOCKER_PORT}:${MYSQL_LOCAL_PORT}
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: